### ISSUE TITLE
Add options to ignore directories

### ISSUE THREAD

**Issue by sametmax** [caioariede/pyq#3]
I ran pyq3 and got:
```
pyq3 "#init_cmd" .
src/foo/bar.py:111 def init_cmd(args):
.tox/py35/lib/python3.5/site-packages/foo/bar.py:89 def init_cmd(args):
.tox/flake8/lib/python3.5/site-packages/foo/bar.py:89 def init_cmd(args):
.tox/coverage/lib/python3.5/site-packages/foo/bar.py:89 def init_cmd(args):
.tox/doc/lib/python3.5/site-packages/foo/bar:89 def init_cmd(args):
```

I don't want to include .tox, it's just noise.

Something like:

```
pyq3 "#init_cmd" . -e ".tox,build,dist,*eggs*" # exclude directories matching these patterns
src/foo/bar.py:111 def init_cmd(args):
```

It would make sense have a sane default value for -e, containing directories any average Python project will have but probably not want to search (although you can if you override pass -e manually).  Such dirs are:

- .tox : environnements tox cache for testing.
- .cache: name for a lot of cache dir (such as pip's)
- build et dist: setuptools build and distribution dirs
- .git/.svn/ etc : most version system dirs.

**Comment by caioariede** [comment]
I agree with you. Some points:

**Currently, `pyq` command do not consider wildcards for path and it should:**

You could avoid hidden files by using: `pyq <selector> *` instead of `pyq <selector> .`

**We should add a `--ignore-dir` option, just like ack:**

`ack --py something --ignore-dir=migrations`

This is extremely useful. I find myself doing this every time with ack.

But well, sometimes I also want to find something in the migrations directory.

**Yes, we should provide sane defaults. I think `ack` defaults is a good start:**

https://github.com/petdance/ack2/blob/44ca211/ConfigDefault.pm#L21

**Comment by caioariede** [comment]
For now you may be able to ignore hidden files by using: `pyq <selector> * `, just like grep.

**Comment by sametmax** [comment]
:)

**Comment by caioariede** [comment]
Fixed in https://github.com/caioariede/pyq/commit/b719ed8c1c2c73165db0335b53b88f60e2c5bb54

**Comment by ksamuel** [comment]
Sweet
